baseURL = 'https://necksurgery.co.nz/'
languageCode = 'en-us'
title = 'Dr Nick Lilic'
theme = "necksurgery"

paginate = 20

[params]
    legal_title = "Dr Nick Lilic"

    # Meta ------------
    description = "Dr Nick Lilic is a New Zealand trained specialist Otolaryngologist, Head and Neck Surgeon."
    keywords = "Dr Nick Lilic, Doctor Nick Lilic, Neck Surgery, Sinuses, ENT, Southern Cross, NIB, ACC, Neck lumps, Mouth and lip lesions, Skin cancer including facial plastics, Salivary gland stones, infections and tumours, Thyroid and parathyroid disorders, Loss of smell, Nasal polyps, Postnasal drip, Rhinitis, Sinus disorders, Blocked ear, Snoring and obstructive sleep apnoea, Swallowing difficulty, Tonsillitis, Tonsil stones, Voice problems"

    # Global settings ------------
    favicon_32 = "/imgs/favicon-32x32.png"
    favicon_16 = "/imgs/favicon-16x16.png"
    
    dateformat = "January 2, 2006"
    
    # layout settings ------------
    headerLayout = "left" # options: left, center, right
    footerLayout = "left" # options: left
    footerNewsletter = true

    # Blog ------------ 
    author = "Dr Nick Lilic"
    info = "Head and Neck Surgeon"

    # analytics
    google_analitycs_id = 'G-79WZ1H9Z52'
    
[taxonomies]
    category = "categories"
    tag = "tags"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

# Menus
# -------------------------------------
# header
[[menu.main]]
    name = "Home"
    weight = 1
    url  = "/"
[[menu.main]]
    name = "Services"
    weight = 2
    url = "/services"
[[menu.main]]
    name = "Contact"
    weight = 3
    url  = "/contact"


# Footer (these add onto the header menu)
# [[menu.footer]]
#     name = "Terms and Conditions"
#     weight = 1
#     url  = "/terms-and-conditions"
[[menu.footer]]
    name = "Privacy policy"
    weight = 1
    url  = "/privacy-policy"


# Social panel (leave empty to hide)
[[menu.social]]
    name = "fab fa-instagram"
    weight = 1
    url  = ""
[[menu.social]]
    name = "lni lni-facebook-original"
    weight = 2
    url  = ""
[[menu.social]]
    name = "fab fa-twitter"
    weight = 3
    url  = "asd"
[[menu.social]]
    name = "fab fa-tiktok"
    weight = 4
    url  = "ticktok"
[[menu.social]]
    name = "fab fa-youtube"
    weight = 5
    url  = "youtube"
[[menu.social]]
    name = "fab fa-linkedin-in"
    weight = 6
    url  = "asd"
[[menu.social]]
    name = "lni lni-envelope"
    weight = 7
    url  = "nick@necksurgery.co.nz"


    